name: MonumentaWarps
main: com.playmonumenta.warps.Plugin
version: 0.01
commands:
  warp:
    permission: warps.warp
    description: Teleports the player to the specified warp.
  warps:
    permission: warps.warp
    description: Lists available warps.
  addwarp:
    permission: warps.addwarp
    description: Creates a new warp at the current location.
  setwarp:
    permission: warps.addwarp
    description: Creates a new warp at the current location.
  delwarp:
    permission: warps.delwarp
    description: Deletes an existing warp.
  back:
    permission: warps.back
    description: Transfers back to location prior to teleporting. Works multiple times in one session. Saves coordinates to /forward.
  forward:
    permission: warps.forward
    description: Transfers forward to location prior to /back. Works multiple times in one session. Saves coordinates to /back.
